version: '3.7'

services:

  kap0:
    image: node:8.12.0-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: node src/kap0.js

  
  cmd:
    image: node:8.12.0-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: /bin/bash